ProductInput:
    type: input-object
    config:
        description: "A product information"
        fields:
            id:
                type: "Int"
                description: "The unique ID of the product."
            name:
                type: "String"
                description: "Name of the product"
            description:
                type: "String"
                description: "Description of the product"
            volume:
                type: "Float"
                description: "Volume of the product, dmÂ³"
            expirationDate:
                type: "DateTime"
                description: "Product expiration date, format dd.mm.yyyy"
            createdAt:
                type: "DateTime"
                description: "Date created, format dd.mm.yyyy hh:mm:ss"
            section:
                type: "SectionEnum"
                description: "Product place location"